# Generated by Django 2.0 on 2018-09-17 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20180916_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=85, verbose_name='Digite seu email'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=85, verbose_name='Digite seu nome'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='senha',
            field=models.CharField(max_length=30, verbose_name='Digite sua senha'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Categoria'),
        ),
    ]
