# Generated by Django 2.1 on 2018-09-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_auto_20180918_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='nada',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=85),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='senha',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Categoria'),
        ),
    ]
