# Generated by Django 2.1 on 2018-09-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_auto_20180919_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nada',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Categoria'),
        ),
    ]
