# Generated by Django 2.1 on 2018-09-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0015_auto_20180924_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='teste',
        ),
        migrations.AddField(
            model_name='clientes',
            name='descricao',
            field=models.CharField(max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='senha2',
            field=models.CharField(max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='senha',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Categoria'),
        ),
    ]
