# Generated by Django 2.1 on 2018-09-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0017_auto_20180924_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='senha2',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Categoria'),
        ),
    ]
