# Generated by Django 2.1 on 2018-10-01 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0029_auto_20180928_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cnpj',
            field=models.BigIntegerField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nomeEmpresa',
            field=models.CharField(max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Categoria'),
        ),
    ]
